name: PR Comment Commands
on:
  issue_comment:
    types: [created]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write

    steps:
      - name: Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          commands: |
            push-image
          repository: poikilotherm/test-image-push-flows
          permission: write
